# Generated by Django 5.0.7 on 2024-07-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_app', '0002_remove_sslcertificate_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sslcertificate',
            old_name='certificate_arn',
            new_name='certificate',
        ),
    ]
