# Generated by Django 5.0.7 on 2024-07-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_app', '0003_rename_certificate_arn_sslcertificate_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcertificate',
            name='private_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='certificate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='hostname',
            field=models.CharField(max_length=255),
        ),
    ]
