apiVersion: v1
kind: Service
metadata:
  name: {{ include "stearmlit.fullname" . }}
  labels:
    {{- include "stearmlit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: {{ .Values.service.protocol}}
      name: http
  selector:
    {{- include "stearmlit.selectorLabels" . | nindent 4 }}
